# title: ARCADE Website
# description: The website for the IROS 24' conference paper: "ARCADE: Scalable Demonstration Collection and Generation via Augmented Reality for Imitation Learning".
# theme: just-the-docs

# url: https://yy-gx.github.io/ARCADE

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template


title: ARCADE Website
description: "ARCADE: Scalable Demonstration Collection and Generation via Augmented Reality for Imitation Learning"
# A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://hri-ironlab.github.io/ARCADE

aux_links:
  Template Repository: https://github.com/hri-ironlab/ARCADE
